// Code generated by ent, DO NOT EDIT.

package regcoininfo

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the regcoininfo type in the database.
	Label = "reg_coin_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEntID holds the string denoting the ent_id field in the database.
	FieldEntID = "ent_id"
	// FieldChainType holds the string denoting the chain_type field in the database.
	FieldChainType = "chain_type"
	// FieldCoinType holds the string denoting the coin_type field in the database.
	FieldCoinType = "coin_type"
	// FieldTempName holds the string denoting the temp_name field in the database.
	FieldTempName = "temp_name"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEnv holds the string denoting the env field in the database.
	FieldEnv = "env"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the regcoininfo in the database.
	Table = "reg_coin_infos"
)

// Columns holds all SQL columns for regcoininfo fields.
var Columns = []string{
	FieldID,
	FieldEntID,
	FieldChainType,
	FieldCoinType,
	FieldTempName,
	FieldName,
	FieldEnv,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEntID holds the default value on creation for the "ent_id" field.
	DefaultEntID func() uuid.UUID
	// DefaultChainType holds the default value on creation for the "chain_type" field.
	DefaultChainType int32
	// DefaultCoinType holds the default value on creation for the "coin_type" field.
	DefaultCoinType int32
	// DefaultTempName holds the default value on creation for the "temp_name" field.
	DefaultTempName string
	// DefaultEnv holds the default value on creation for the "env" field.
	DefaultEnv string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
)
