// Code generated by ent, DO NOT EDIT.

package transaction

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the transaction type in the database.
	Label = "transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEntID holds the string denoting the ent_id field in the database.
	FieldEntID = "ent_id"
	// FieldCoinType holds the string denoting the coin_type field in the database.
	FieldCoinType = "coin_type"
	// FieldChainType holds the string denoting the chain_type field in the database.
	FieldChainType = "chain_type"
	// FieldClientType holds the string denoting the client_type field in the database.
	FieldClientType = "client_type"
	// FieldTransactionID holds the string denoting the transaction_id field in the database.
	FieldTransactionID = "transaction_id"
	// FieldCid holds the string denoting the cid field in the database.
	FieldCid = "cid"
	// FieldExitCode holds the string denoting the exit_code field in the database.
	FieldExitCode = "exit_code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFrom holds the string denoting the from field in the database.
	FieldFrom = "from"
	// FieldTo holds the string denoting the to field in the database.
	FieldTo = "to"
	// FieldMemo holds the string denoting the memo field in the database.
	FieldMemo = "memo"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldLockTime holds the string denoting the lock_time field in the database.
	FieldLockTime = "lock_time"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the transaction in the database.
	Table = "transactions"
)

// Columns holds all SQL columns for transaction fields.
var Columns = []string{
	FieldID,
	FieldEntID,
	FieldCoinType,
	FieldChainType,
	FieldClientType,
	FieldTransactionID,
	FieldCid,
	FieldExitCode,
	FieldName,
	FieldFrom,
	FieldTo,
	FieldMemo,
	FieldAmount,
	FieldPayload,
	FieldState,
	FieldLockTime,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEntID holds the default value on creation for the "ent_id" field.
	DefaultEntID func() uuid.UUID
	// DefaultCoinType holds the default value on creation for the "coin_type" field.
	DefaultCoinType int32
	// DefaultChainType holds the default value on creation for the "chain_type" field.
	DefaultChainType int32
	// DefaultClientType holds the default value on creation for the "client_type" field.
	DefaultClientType int32
	// DefaultCid holds the default value on creation for the "cid" field.
	DefaultCid string
	// DefaultExitCode holds the default value on creation for the "exit_code" field.
	DefaultExitCode int64
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultFrom holds the default value on creation for the "from" field.
	DefaultFrom string
	// DefaultTo holds the default value on creation for the "to" field.
	DefaultTo string
	// DefaultMemo holds the default value on creation for the "memo" field.
	DefaultMemo string
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount uint64
	// DefaultPayload holds the default value on creation for the "payload" field.
	DefaultPayload []byte
	// PayloadValidator is a validator for the "payload" field. It is called by the builders before save.
	PayloadValidator func([]byte) error
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState int32
	// DefaultLockTime holds the default value on creation for the "lock_time" field.
	DefaultLockTime uint32
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
)
