// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/fox-proxy/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/fox-proxy/pkg/db/ent/regcoininfo"
)

// RegCoinInfoDelete is the builder for deleting a RegCoinInfo entity.
type RegCoinInfoDelete struct {
	config
	hooks    []Hook
	mutation *RegCoinInfoMutation
}

// Where appends a list predicates to the RegCoinInfoDelete builder.
func (rcid *RegCoinInfoDelete) Where(ps ...predicate.RegCoinInfo) *RegCoinInfoDelete {
	rcid.mutation.Where(ps...)
	return rcid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rcid *RegCoinInfoDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rcid.hooks) == 0 {
		affected, err = rcid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RegCoinInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rcid.mutation = mutation
			affected, err = rcid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rcid.hooks) - 1; i >= 0; i-- {
			if rcid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rcid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rcid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcid *RegCoinInfoDelete) ExecX(ctx context.Context) int {
	n, err := rcid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rcid *RegCoinInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: regcoininfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: regcoininfo.FieldID,
			},
		},
	}
	if ps := rcid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rcid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// RegCoinInfoDeleteOne is the builder for deleting a single RegCoinInfo entity.
type RegCoinInfoDeleteOne struct {
	rcid *RegCoinInfoDelete
}

// Exec executes the deletion query.
func (rcido *RegCoinInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := rcido.rcid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{regcoininfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rcido *RegCoinInfoDeleteOne) ExecX(ctx context.Context) {
	rcido.rcid.ExecX(ctx)
}
