// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/fox-proxy/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/fox-proxy/pkg/db/ent/regcoininfo"
)

// RegCoinInfoQuery is the builder for querying RegCoinInfo entities.
type RegCoinInfoQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.RegCoinInfo
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RegCoinInfoQuery builder.
func (rciq *RegCoinInfoQuery) Where(ps ...predicate.RegCoinInfo) *RegCoinInfoQuery {
	rciq.predicates = append(rciq.predicates, ps...)
	return rciq
}

// Limit adds a limit step to the query.
func (rciq *RegCoinInfoQuery) Limit(limit int) *RegCoinInfoQuery {
	rciq.limit = &limit
	return rciq
}

// Offset adds an offset step to the query.
func (rciq *RegCoinInfoQuery) Offset(offset int) *RegCoinInfoQuery {
	rciq.offset = &offset
	return rciq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rciq *RegCoinInfoQuery) Unique(unique bool) *RegCoinInfoQuery {
	rciq.unique = &unique
	return rciq
}

// Order adds an order step to the query.
func (rciq *RegCoinInfoQuery) Order(o ...OrderFunc) *RegCoinInfoQuery {
	rciq.order = append(rciq.order, o...)
	return rciq
}

// First returns the first RegCoinInfo entity from the query.
// Returns a *NotFoundError when no RegCoinInfo was found.
func (rciq *RegCoinInfoQuery) First(ctx context.Context) (*RegCoinInfo, error) {
	nodes, err := rciq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{regcoininfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rciq *RegCoinInfoQuery) FirstX(ctx context.Context) *RegCoinInfo {
	node, err := rciq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RegCoinInfo ID from the query.
// Returns a *NotFoundError when no RegCoinInfo ID was found.
func (rciq *RegCoinInfoQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = rciq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{regcoininfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rciq *RegCoinInfoQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := rciq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RegCoinInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RegCoinInfo entity is found.
// Returns a *NotFoundError when no RegCoinInfo entities are found.
func (rciq *RegCoinInfoQuery) Only(ctx context.Context) (*RegCoinInfo, error) {
	nodes, err := rciq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{regcoininfo.Label}
	default:
		return nil, &NotSingularError{regcoininfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rciq *RegCoinInfoQuery) OnlyX(ctx context.Context) *RegCoinInfo {
	node, err := rciq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RegCoinInfo ID in the query.
// Returns a *NotSingularError when more than one RegCoinInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (rciq *RegCoinInfoQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = rciq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{regcoininfo.Label}
	default:
		err = &NotSingularError{regcoininfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rciq *RegCoinInfoQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := rciq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RegCoinInfos.
func (rciq *RegCoinInfoQuery) All(ctx context.Context) ([]*RegCoinInfo, error) {
	if err := rciq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rciq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rciq *RegCoinInfoQuery) AllX(ctx context.Context) []*RegCoinInfo {
	nodes, err := rciq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RegCoinInfo IDs.
func (rciq *RegCoinInfoQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := rciq.Select(regcoininfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rciq *RegCoinInfoQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := rciq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rciq *RegCoinInfoQuery) Count(ctx context.Context) (int, error) {
	if err := rciq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rciq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rciq *RegCoinInfoQuery) CountX(ctx context.Context) int {
	count, err := rciq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rciq *RegCoinInfoQuery) Exist(ctx context.Context) (bool, error) {
	if err := rciq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rciq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rciq *RegCoinInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := rciq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RegCoinInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rciq *RegCoinInfoQuery) Clone() *RegCoinInfoQuery {
	if rciq == nil {
		return nil
	}
	return &RegCoinInfoQuery{
		config:     rciq.config,
		limit:      rciq.limit,
		offset:     rciq.offset,
		order:      append([]OrderFunc{}, rciq.order...),
		predicates: append([]predicate.RegCoinInfo{}, rciq.predicates...),
		// clone intermediate query.
		sql:    rciq.sql.Clone(),
		path:   rciq.path,
		unique: rciq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EntID uuid.UUID `json:"ent_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RegCoinInfo.Query().
//		GroupBy(regcoininfo.FieldEntID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (rciq *RegCoinInfoQuery) GroupBy(field string, fields ...string) *RegCoinInfoGroupBy {
	grbuild := &RegCoinInfoGroupBy{config: rciq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rciq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rciq.sqlQuery(ctx), nil
	}
	grbuild.label = regcoininfo.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EntID uuid.UUID `json:"ent_id,omitempty"`
//	}
//
//	client.RegCoinInfo.Query().
//		Select(regcoininfo.FieldEntID).
//		Scan(ctx, &v)
//
func (rciq *RegCoinInfoQuery) Select(fields ...string) *RegCoinInfoSelect {
	rciq.fields = append(rciq.fields, fields...)
	selbuild := &RegCoinInfoSelect{RegCoinInfoQuery: rciq}
	selbuild.label = regcoininfo.Label
	selbuild.flds, selbuild.scan = &rciq.fields, selbuild.Scan
	return selbuild
}

func (rciq *RegCoinInfoQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rciq.fields {
		if !regcoininfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rciq.path != nil {
		prev, err := rciq.path(ctx)
		if err != nil {
			return err
		}
		rciq.sql = prev
	}
	return nil
}

func (rciq *RegCoinInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RegCoinInfo, error) {
	var (
		nodes = []*RegCoinInfo{}
		_spec = rciq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*RegCoinInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &RegCoinInfo{config: rciq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(rciq.modifiers) > 0 {
		_spec.Modifiers = rciq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rciq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rciq *RegCoinInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rciq.querySpec()
	if len(rciq.modifiers) > 0 {
		_spec.Modifiers = rciq.modifiers
	}
	_spec.Node.Columns = rciq.fields
	if len(rciq.fields) > 0 {
		_spec.Unique = rciq.unique != nil && *rciq.unique
	}
	return sqlgraph.CountNodes(ctx, rciq.driver, _spec)
}

func (rciq *RegCoinInfoQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rciq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (rciq *RegCoinInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   regcoininfo.Table,
			Columns: regcoininfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: regcoininfo.FieldID,
			},
		},
		From:   rciq.sql,
		Unique: true,
	}
	if unique := rciq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rciq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, regcoininfo.FieldID)
		for i := range fields {
			if fields[i] != regcoininfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rciq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rciq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rciq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rciq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rciq *RegCoinInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rciq.driver.Dialect())
	t1 := builder.Table(regcoininfo.Table)
	columns := rciq.fields
	if len(columns) == 0 {
		columns = regcoininfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rciq.sql != nil {
		selector = rciq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rciq.unique != nil && *rciq.unique {
		selector.Distinct()
	}
	for _, m := range rciq.modifiers {
		m(selector)
	}
	for _, p := range rciq.predicates {
		p(selector)
	}
	for _, p := range rciq.order {
		p(selector)
	}
	if offset := rciq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rciq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (rciq *RegCoinInfoQuery) ForUpdate(opts ...sql.LockOption) *RegCoinInfoQuery {
	if rciq.driver.Dialect() == dialect.Postgres {
		rciq.Unique(false)
	}
	rciq.modifiers = append(rciq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return rciq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (rciq *RegCoinInfoQuery) ForShare(opts ...sql.LockOption) *RegCoinInfoQuery {
	if rciq.driver.Dialect() == dialect.Postgres {
		rciq.Unique(false)
	}
	rciq.modifiers = append(rciq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return rciq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rciq *RegCoinInfoQuery) Modify(modifiers ...func(s *sql.Selector)) *RegCoinInfoSelect {
	rciq.modifiers = append(rciq.modifiers, modifiers...)
	return rciq.Select()
}

// RegCoinInfoGroupBy is the group-by builder for RegCoinInfo entities.
type RegCoinInfoGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rcigb *RegCoinInfoGroupBy) Aggregate(fns ...AggregateFunc) *RegCoinInfoGroupBy {
	rcigb.fns = append(rcigb.fns, fns...)
	return rcigb
}

// Scan applies the group-by query and scans the result into the given value.
func (rcigb *RegCoinInfoGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rcigb.path(ctx)
	if err != nil {
		return err
	}
	rcigb.sql = query
	return rcigb.sqlScan(ctx, v)
}

func (rcigb *RegCoinInfoGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rcigb.fields {
		if !regcoininfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rcigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rcigb *RegCoinInfoGroupBy) sqlQuery() *sql.Selector {
	selector := rcigb.sql.Select()
	aggregation := make([]string, 0, len(rcigb.fns))
	for _, fn := range rcigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rcigb.fields)+len(rcigb.fns))
		for _, f := range rcigb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rcigb.fields...)...)
}

// RegCoinInfoSelect is the builder for selecting fields of RegCoinInfo entities.
type RegCoinInfoSelect struct {
	*RegCoinInfoQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rcis *RegCoinInfoSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rcis.prepareQuery(ctx); err != nil {
		return err
	}
	rcis.sql = rcis.RegCoinInfoQuery.sqlQuery(ctx)
	return rcis.sqlScan(ctx, v)
}

func (rcis *RegCoinInfoSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rcis.sql.Query()
	if err := rcis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rcis *RegCoinInfoSelect) Modify(modifiers ...func(s *sql.Selector)) *RegCoinInfoSelect {
	rcis.modifiers = append(rcis.modifiers, modifiers...)
	return rcis
}
