// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/fox-proxy/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/fox-proxy/pkg/db/ent/transaction"
	"github.com/google/uuid"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks     []Hook
	mutation  *TransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TransactionUpdate builder.
func (tu *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetEntID sets the "ent_id" field.
func (tu *TransactionUpdate) SetEntID(u uuid.UUID) *TransactionUpdate {
	tu.mutation.SetEntID(u)
	return tu
}

// SetNillableEntID sets the "ent_id" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableEntID(u *uuid.UUID) *TransactionUpdate {
	if u != nil {
		tu.SetEntID(*u)
	}
	return tu
}

// SetCoinType sets the "coin_type" field.
func (tu *TransactionUpdate) SetCoinType(i int32) *TransactionUpdate {
	tu.mutation.ResetCoinType()
	tu.mutation.SetCoinType(i)
	return tu
}

// SetNillableCoinType sets the "coin_type" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableCoinType(i *int32) *TransactionUpdate {
	if i != nil {
		tu.SetCoinType(*i)
	}
	return tu
}

// AddCoinType adds i to the "coin_type" field.
func (tu *TransactionUpdate) AddCoinType(i int32) *TransactionUpdate {
	tu.mutation.AddCoinType(i)
	return tu
}

// ClearCoinType clears the value of the "coin_type" field.
func (tu *TransactionUpdate) ClearCoinType() *TransactionUpdate {
	tu.mutation.ClearCoinType()
	return tu
}

// SetChainType sets the "chain_type" field.
func (tu *TransactionUpdate) SetChainType(i int32) *TransactionUpdate {
	tu.mutation.ResetChainType()
	tu.mutation.SetChainType(i)
	return tu
}

// SetNillableChainType sets the "chain_type" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableChainType(i *int32) *TransactionUpdate {
	if i != nil {
		tu.SetChainType(*i)
	}
	return tu
}

// AddChainType adds i to the "chain_type" field.
func (tu *TransactionUpdate) AddChainType(i int32) *TransactionUpdate {
	tu.mutation.AddChainType(i)
	return tu
}

// ClearChainType clears the value of the "chain_type" field.
func (tu *TransactionUpdate) ClearChainType() *TransactionUpdate {
	tu.mutation.ClearChainType()
	return tu
}

// SetClientType sets the "client_type" field.
func (tu *TransactionUpdate) SetClientType(i int32) *TransactionUpdate {
	tu.mutation.ResetClientType()
	tu.mutation.SetClientType(i)
	return tu
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableClientType(i *int32) *TransactionUpdate {
	if i != nil {
		tu.SetClientType(*i)
	}
	return tu
}

// AddClientType adds i to the "client_type" field.
func (tu *TransactionUpdate) AddClientType(i int32) *TransactionUpdate {
	tu.mutation.AddClientType(i)
	return tu
}

// ClearClientType clears the value of the "client_type" field.
func (tu *TransactionUpdate) ClearClientType() *TransactionUpdate {
	tu.mutation.ClearClientType()
	return tu
}

// SetTransactionID sets the "transaction_id" field.
func (tu *TransactionUpdate) SetTransactionID(s string) *TransactionUpdate {
	tu.mutation.SetTransactionID(s)
	return tu
}

// SetCid sets the "cid" field.
func (tu *TransactionUpdate) SetCid(s string) *TransactionUpdate {
	tu.mutation.SetCid(s)
	return tu
}

// SetNillableCid sets the "cid" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableCid(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetCid(*s)
	}
	return tu
}

// ClearCid clears the value of the "cid" field.
func (tu *TransactionUpdate) ClearCid() *TransactionUpdate {
	tu.mutation.ClearCid()
	return tu
}

// SetExitCode sets the "exit_code" field.
func (tu *TransactionUpdate) SetExitCode(i int64) *TransactionUpdate {
	tu.mutation.ResetExitCode()
	tu.mutation.SetExitCode(i)
	return tu
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableExitCode(i *int64) *TransactionUpdate {
	if i != nil {
		tu.SetExitCode(*i)
	}
	return tu
}

// AddExitCode adds i to the "exit_code" field.
func (tu *TransactionUpdate) AddExitCode(i int64) *TransactionUpdate {
	tu.mutation.AddExitCode(i)
	return tu
}

// ClearExitCode clears the value of the "exit_code" field.
func (tu *TransactionUpdate) ClearExitCode() *TransactionUpdate {
	tu.mutation.ClearExitCode()
	return tu
}

// SetName sets the "name" field.
func (tu *TransactionUpdate) SetName(s string) *TransactionUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableName(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// ClearName clears the value of the "name" field.
func (tu *TransactionUpdate) ClearName() *TransactionUpdate {
	tu.mutation.ClearName()
	return tu
}

// SetFrom sets the "from" field.
func (tu *TransactionUpdate) SetFrom(s string) *TransactionUpdate {
	tu.mutation.SetFrom(s)
	return tu
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableFrom(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetFrom(*s)
	}
	return tu
}

// ClearFrom clears the value of the "from" field.
func (tu *TransactionUpdate) ClearFrom() *TransactionUpdate {
	tu.mutation.ClearFrom()
	return tu
}

// SetTo sets the "to" field.
func (tu *TransactionUpdate) SetTo(s string) *TransactionUpdate {
	tu.mutation.SetTo(s)
	return tu
}

// SetNillableTo sets the "to" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableTo(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetTo(*s)
	}
	return tu
}

// ClearTo clears the value of the "to" field.
func (tu *TransactionUpdate) ClearTo() *TransactionUpdate {
	tu.mutation.ClearTo()
	return tu
}

// SetMemo sets the "memo" field.
func (tu *TransactionUpdate) SetMemo(s string) *TransactionUpdate {
	tu.mutation.SetMemo(s)
	return tu
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableMemo(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetMemo(*s)
	}
	return tu
}

// ClearMemo clears the value of the "memo" field.
func (tu *TransactionUpdate) ClearMemo() *TransactionUpdate {
	tu.mutation.ClearMemo()
	return tu
}

// SetAmount sets the "amount" field.
func (tu *TransactionUpdate) SetAmount(u uint64) *TransactionUpdate {
	tu.mutation.ResetAmount()
	tu.mutation.SetAmount(u)
	return tu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableAmount(u *uint64) *TransactionUpdate {
	if u != nil {
		tu.SetAmount(*u)
	}
	return tu
}

// AddAmount adds u to the "amount" field.
func (tu *TransactionUpdate) AddAmount(u int64) *TransactionUpdate {
	tu.mutation.AddAmount(u)
	return tu
}

// ClearAmount clears the value of the "amount" field.
func (tu *TransactionUpdate) ClearAmount() *TransactionUpdate {
	tu.mutation.ClearAmount()
	return tu
}

// SetPayload sets the "payload" field.
func (tu *TransactionUpdate) SetPayload(b []byte) *TransactionUpdate {
	tu.mutation.SetPayload(b)
	return tu
}

// ClearPayload clears the value of the "payload" field.
func (tu *TransactionUpdate) ClearPayload() *TransactionUpdate {
	tu.mutation.ClearPayload()
	return tu
}

// SetState sets the "state" field.
func (tu *TransactionUpdate) SetState(i int32) *TransactionUpdate {
	tu.mutation.ResetState()
	tu.mutation.SetState(i)
	return tu
}

// SetNillableState sets the "state" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableState(i *int32) *TransactionUpdate {
	if i != nil {
		tu.SetState(*i)
	}
	return tu
}

// AddState adds i to the "state" field.
func (tu *TransactionUpdate) AddState(i int32) *TransactionUpdate {
	tu.mutation.AddState(i)
	return tu
}

// ClearState clears the value of the "state" field.
func (tu *TransactionUpdate) ClearState() *TransactionUpdate {
	tu.mutation.ClearState()
	return tu
}

// SetLockTime sets the "lock_time" field.
func (tu *TransactionUpdate) SetLockTime(u uint32) *TransactionUpdate {
	tu.mutation.ResetLockTime()
	tu.mutation.SetLockTime(u)
	return tu
}

// SetNillableLockTime sets the "lock_time" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableLockTime(u *uint32) *TransactionUpdate {
	if u != nil {
		tu.SetLockTime(*u)
	}
	return tu
}

// AddLockTime adds u to the "lock_time" field.
func (tu *TransactionUpdate) AddLockTime(u int32) *TransactionUpdate {
	tu.mutation.AddLockTime(u)
	return tu
}

// ClearLockTime clears the value of the "lock_time" field.
func (tu *TransactionUpdate) ClearLockTime() *TransactionUpdate {
	tu.mutation.ClearLockTime()
	return tu
}

// SetCreatedAt sets the "created_at" field.
func (tu *TransactionUpdate) SetCreatedAt(u uint32) *TransactionUpdate {
	tu.mutation.ResetCreatedAt()
	tu.mutation.SetCreatedAt(u)
	return tu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableCreatedAt(u *uint32) *TransactionUpdate {
	if u != nil {
		tu.SetCreatedAt(*u)
	}
	return tu
}

// AddCreatedAt adds u to the "created_at" field.
func (tu *TransactionUpdate) AddCreatedAt(u int32) *TransactionUpdate {
	tu.mutation.AddCreatedAt(u)
	return tu
}

// ClearCreatedAt clears the value of the "created_at" field.
func (tu *TransactionUpdate) ClearCreatedAt() *TransactionUpdate {
	tu.mutation.ClearCreatedAt()
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TransactionUpdate) SetUpdatedAt(u uint32) *TransactionUpdate {
	tu.mutation.ResetUpdatedAt()
	tu.mutation.SetUpdatedAt(u)
	return tu
}

// AddUpdatedAt adds u to the "updated_at" field.
func (tu *TransactionUpdate) AddUpdatedAt(u int32) *TransactionUpdate {
	tu.mutation.AddUpdatedAt(u)
	return tu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (tu *TransactionUpdate) ClearUpdatedAt() *TransactionUpdate {
	tu.mutation.ClearUpdatedAt()
	return tu
}

// SetDeletedAt sets the "deleted_at" field.
func (tu *TransactionUpdate) SetDeletedAt(u uint32) *TransactionUpdate {
	tu.mutation.ResetDeletedAt()
	tu.mutation.SetDeletedAt(u)
	return tu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableDeletedAt(u *uint32) *TransactionUpdate {
	if u != nil {
		tu.SetDeletedAt(*u)
	}
	return tu
}

// AddDeletedAt adds u to the "deleted_at" field.
func (tu *TransactionUpdate) AddDeletedAt(u int32) *TransactionUpdate {
	tu.mutation.AddDeletedAt(u)
	return tu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (tu *TransactionUpdate) ClearDeletedAt() *TransactionUpdate {
	tu.mutation.ClearDeletedAt()
	return tu
}

// Mutation returns the TransactionMutation object of the builder.
func (tu *TransactionUpdate) Mutation() *TransactionMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TransactionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	tu.defaults()
	if len(tu.hooks) == 0 {
		if err = tu.check(); err != nil {
			return 0, err
		}
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransactionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tu.check(); err != nil {
				return 0, err
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			if tu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TransactionUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TransactionUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok && !tu.mutation.UpdatedAtCleared() {
		v := transaction.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TransactionUpdate) check() error {
	if v, ok := tu.mutation.Payload(); ok {
		if err := transaction.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "Transaction.payload": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tu *TransactionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransactionUpdate {
	tu.modifiers = append(tu.modifiers, modifiers...)
	return tu
}

func (tu *TransactionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   transaction.Table,
			Columns: transaction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: transaction.FieldID,
			},
		},
	}
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.EntID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: transaction.FieldEntID,
		})
	}
	if value, ok := tu.mutation.CoinType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldCoinType,
		})
	}
	if value, ok := tu.mutation.AddedCoinType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldCoinType,
		})
	}
	if tu.mutation.CoinTypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: transaction.FieldCoinType,
		})
	}
	if value, ok := tu.mutation.ChainType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldChainType,
		})
	}
	if value, ok := tu.mutation.AddedChainType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldChainType,
		})
	}
	if tu.mutation.ChainTypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: transaction.FieldChainType,
		})
	}
	if value, ok := tu.mutation.ClientType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldClientType,
		})
	}
	if value, ok := tu.mutation.AddedClientType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldClientType,
		})
	}
	if tu.mutation.ClientTypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: transaction.FieldClientType,
		})
	}
	if value, ok := tu.mutation.TransactionID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldTransactionID,
		})
	}
	if value, ok := tu.mutation.Cid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldCid,
		})
	}
	if tu.mutation.CidCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: transaction.FieldCid,
		})
	}
	if value, ok := tu.mutation.ExitCode(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: transaction.FieldExitCode,
		})
	}
	if value, ok := tu.mutation.AddedExitCode(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: transaction.FieldExitCode,
		})
	}
	if tu.mutation.ExitCodeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Column: transaction.FieldExitCode,
		})
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldName,
		})
	}
	if tu.mutation.NameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: transaction.FieldName,
		})
	}
	if value, ok := tu.mutation.From(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldFrom,
		})
	}
	if tu.mutation.FromCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: transaction.FieldFrom,
		})
	}
	if value, ok := tu.mutation.To(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldTo,
		})
	}
	if tu.mutation.ToCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: transaction.FieldTo,
		})
	}
	if value, ok := tu.mutation.Memo(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldMemo,
		})
	}
	if tu.mutation.MemoCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: transaction.FieldMemo,
		})
	}
	if value, ok := tu.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: transaction.FieldAmount,
		})
	}
	if value, ok := tu.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: transaction.FieldAmount,
		})
	}
	if tu.mutation.AmountCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Column: transaction.FieldAmount,
		})
	}
	if value, ok := tu.mutation.Payload(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: transaction.FieldPayload,
		})
	}
	if tu.mutation.PayloadCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Column: transaction.FieldPayload,
		})
	}
	if value, ok := tu.mutation.State(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldState,
		})
	}
	if value, ok := tu.mutation.AddedState(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldState,
		})
	}
	if tu.mutation.StateCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: transaction.FieldState,
		})
	}
	if value, ok := tu.mutation.LockTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldLockTime,
		})
	}
	if value, ok := tu.mutation.AddedLockTime(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldLockTime,
		})
	}
	if tu.mutation.LockTimeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: transaction.FieldLockTime,
		})
	}
	if value, ok := tu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldCreatedAt,
		})
	}
	if value, ok := tu.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldCreatedAt,
		})
	}
	if tu.mutation.CreatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: transaction.FieldCreatedAt,
		})
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldUpdatedAt,
		})
	}
	if value, ok := tu.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldUpdatedAt,
		})
	}
	if tu.mutation.UpdatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: transaction.FieldUpdatedAt,
		})
	}
	if value, ok := tu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldDeletedAt,
		})
	}
	if value, ok := tu.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldDeletedAt,
		})
	}
	if tu.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: transaction.FieldDeletedAt,
		})
	}
	_spec.Modifiers = tu.modifiers
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetEntID sets the "ent_id" field.
func (tuo *TransactionUpdateOne) SetEntID(u uuid.UUID) *TransactionUpdateOne {
	tuo.mutation.SetEntID(u)
	return tuo
}

// SetNillableEntID sets the "ent_id" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableEntID(u *uuid.UUID) *TransactionUpdateOne {
	if u != nil {
		tuo.SetEntID(*u)
	}
	return tuo
}

// SetCoinType sets the "coin_type" field.
func (tuo *TransactionUpdateOne) SetCoinType(i int32) *TransactionUpdateOne {
	tuo.mutation.ResetCoinType()
	tuo.mutation.SetCoinType(i)
	return tuo
}

// SetNillableCoinType sets the "coin_type" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableCoinType(i *int32) *TransactionUpdateOne {
	if i != nil {
		tuo.SetCoinType(*i)
	}
	return tuo
}

// AddCoinType adds i to the "coin_type" field.
func (tuo *TransactionUpdateOne) AddCoinType(i int32) *TransactionUpdateOne {
	tuo.mutation.AddCoinType(i)
	return tuo
}

// ClearCoinType clears the value of the "coin_type" field.
func (tuo *TransactionUpdateOne) ClearCoinType() *TransactionUpdateOne {
	tuo.mutation.ClearCoinType()
	return tuo
}

// SetChainType sets the "chain_type" field.
func (tuo *TransactionUpdateOne) SetChainType(i int32) *TransactionUpdateOne {
	tuo.mutation.ResetChainType()
	tuo.mutation.SetChainType(i)
	return tuo
}

// SetNillableChainType sets the "chain_type" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableChainType(i *int32) *TransactionUpdateOne {
	if i != nil {
		tuo.SetChainType(*i)
	}
	return tuo
}

// AddChainType adds i to the "chain_type" field.
func (tuo *TransactionUpdateOne) AddChainType(i int32) *TransactionUpdateOne {
	tuo.mutation.AddChainType(i)
	return tuo
}

// ClearChainType clears the value of the "chain_type" field.
func (tuo *TransactionUpdateOne) ClearChainType() *TransactionUpdateOne {
	tuo.mutation.ClearChainType()
	return tuo
}

// SetClientType sets the "client_type" field.
func (tuo *TransactionUpdateOne) SetClientType(i int32) *TransactionUpdateOne {
	tuo.mutation.ResetClientType()
	tuo.mutation.SetClientType(i)
	return tuo
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableClientType(i *int32) *TransactionUpdateOne {
	if i != nil {
		tuo.SetClientType(*i)
	}
	return tuo
}

// AddClientType adds i to the "client_type" field.
func (tuo *TransactionUpdateOne) AddClientType(i int32) *TransactionUpdateOne {
	tuo.mutation.AddClientType(i)
	return tuo
}

// ClearClientType clears the value of the "client_type" field.
func (tuo *TransactionUpdateOne) ClearClientType() *TransactionUpdateOne {
	tuo.mutation.ClearClientType()
	return tuo
}

// SetTransactionID sets the "transaction_id" field.
func (tuo *TransactionUpdateOne) SetTransactionID(s string) *TransactionUpdateOne {
	tuo.mutation.SetTransactionID(s)
	return tuo
}

// SetCid sets the "cid" field.
func (tuo *TransactionUpdateOne) SetCid(s string) *TransactionUpdateOne {
	tuo.mutation.SetCid(s)
	return tuo
}

// SetNillableCid sets the "cid" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableCid(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetCid(*s)
	}
	return tuo
}

// ClearCid clears the value of the "cid" field.
func (tuo *TransactionUpdateOne) ClearCid() *TransactionUpdateOne {
	tuo.mutation.ClearCid()
	return tuo
}

// SetExitCode sets the "exit_code" field.
func (tuo *TransactionUpdateOne) SetExitCode(i int64) *TransactionUpdateOne {
	tuo.mutation.ResetExitCode()
	tuo.mutation.SetExitCode(i)
	return tuo
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableExitCode(i *int64) *TransactionUpdateOne {
	if i != nil {
		tuo.SetExitCode(*i)
	}
	return tuo
}

// AddExitCode adds i to the "exit_code" field.
func (tuo *TransactionUpdateOne) AddExitCode(i int64) *TransactionUpdateOne {
	tuo.mutation.AddExitCode(i)
	return tuo
}

// ClearExitCode clears the value of the "exit_code" field.
func (tuo *TransactionUpdateOne) ClearExitCode() *TransactionUpdateOne {
	tuo.mutation.ClearExitCode()
	return tuo
}

// SetName sets the "name" field.
func (tuo *TransactionUpdateOne) SetName(s string) *TransactionUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableName(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// ClearName clears the value of the "name" field.
func (tuo *TransactionUpdateOne) ClearName() *TransactionUpdateOne {
	tuo.mutation.ClearName()
	return tuo
}

// SetFrom sets the "from" field.
func (tuo *TransactionUpdateOne) SetFrom(s string) *TransactionUpdateOne {
	tuo.mutation.SetFrom(s)
	return tuo
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableFrom(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetFrom(*s)
	}
	return tuo
}

// ClearFrom clears the value of the "from" field.
func (tuo *TransactionUpdateOne) ClearFrom() *TransactionUpdateOne {
	tuo.mutation.ClearFrom()
	return tuo
}

// SetTo sets the "to" field.
func (tuo *TransactionUpdateOne) SetTo(s string) *TransactionUpdateOne {
	tuo.mutation.SetTo(s)
	return tuo
}

// SetNillableTo sets the "to" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableTo(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetTo(*s)
	}
	return tuo
}

// ClearTo clears the value of the "to" field.
func (tuo *TransactionUpdateOne) ClearTo() *TransactionUpdateOne {
	tuo.mutation.ClearTo()
	return tuo
}

// SetMemo sets the "memo" field.
func (tuo *TransactionUpdateOne) SetMemo(s string) *TransactionUpdateOne {
	tuo.mutation.SetMemo(s)
	return tuo
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableMemo(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetMemo(*s)
	}
	return tuo
}

// ClearMemo clears the value of the "memo" field.
func (tuo *TransactionUpdateOne) ClearMemo() *TransactionUpdateOne {
	tuo.mutation.ClearMemo()
	return tuo
}

// SetAmount sets the "amount" field.
func (tuo *TransactionUpdateOne) SetAmount(u uint64) *TransactionUpdateOne {
	tuo.mutation.ResetAmount()
	tuo.mutation.SetAmount(u)
	return tuo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableAmount(u *uint64) *TransactionUpdateOne {
	if u != nil {
		tuo.SetAmount(*u)
	}
	return tuo
}

// AddAmount adds u to the "amount" field.
func (tuo *TransactionUpdateOne) AddAmount(u int64) *TransactionUpdateOne {
	tuo.mutation.AddAmount(u)
	return tuo
}

// ClearAmount clears the value of the "amount" field.
func (tuo *TransactionUpdateOne) ClearAmount() *TransactionUpdateOne {
	tuo.mutation.ClearAmount()
	return tuo
}

// SetPayload sets the "payload" field.
func (tuo *TransactionUpdateOne) SetPayload(b []byte) *TransactionUpdateOne {
	tuo.mutation.SetPayload(b)
	return tuo
}

// ClearPayload clears the value of the "payload" field.
func (tuo *TransactionUpdateOne) ClearPayload() *TransactionUpdateOne {
	tuo.mutation.ClearPayload()
	return tuo
}

// SetState sets the "state" field.
func (tuo *TransactionUpdateOne) SetState(i int32) *TransactionUpdateOne {
	tuo.mutation.ResetState()
	tuo.mutation.SetState(i)
	return tuo
}

// SetNillableState sets the "state" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableState(i *int32) *TransactionUpdateOne {
	if i != nil {
		tuo.SetState(*i)
	}
	return tuo
}

// AddState adds i to the "state" field.
func (tuo *TransactionUpdateOne) AddState(i int32) *TransactionUpdateOne {
	tuo.mutation.AddState(i)
	return tuo
}

// ClearState clears the value of the "state" field.
func (tuo *TransactionUpdateOne) ClearState() *TransactionUpdateOne {
	tuo.mutation.ClearState()
	return tuo
}

// SetLockTime sets the "lock_time" field.
func (tuo *TransactionUpdateOne) SetLockTime(u uint32) *TransactionUpdateOne {
	tuo.mutation.ResetLockTime()
	tuo.mutation.SetLockTime(u)
	return tuo
}

// SetNillableLockTime sets the "lock_time" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableLockTime(u *uint32) *TransactionUpdateOne {
	if u != nil {
		tuo.SetLockTime(*u)
	}
	return tuo
}

// AddLockTime adds u to the "lock_time" field.
func (tuo *TransactionUpdateOne) AddLockTime(u int32) *TransactionUpdateOne {
	tuo.mutation.AddLockTime(u)
	return tuo
}

// ClearLockTime clears the value of the "lock_time" field.
func (tuo *TransactionUpdateOne) ClearLockTime() *TransactionUpdateOne {
	tuo.mutation.ClearLockTime()
	return tuo
}

// SetCreatedAt sets the "created_at" field.
func (tuo *TransactionUpdateOne) SetCreatedAt(u uint32) *TransactionUpdateOne {
	tuo.mutation.ResetCreatedAt()
	tuo.mutation.SetCreatedAt(u)
	return tuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableCreatedAt(u *uint32) *TransactionUpdateOne {
	if u != nil {
		tuo.SetCreatedAt(*u)
	}
	return tuo
}

// AddCreatedAt adds u to the "created_at" field.
func (tuo *TransactionUpdateOne) AddCreatedAt(u int32) *TransactionUpdateOne {
	tuo.mutation.AddCreatedAt(u)
	return tuo
}

// ClearCreatedAt clears the value of the "created_at" field.
func (tuo *TransactionUpdateOne) ClearCreatedAt() *TransactionUpdateOne {
	tuo.mutation.ClearCreatedAt()
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TransactionUpdateOne) SetUpdatedAt(u uint32) *TransactionUpdateOne {
	tuo.mutation.ResetUpdatedAt()
	tuo.mutation.SetUpdatedAt(u)
	return tuo
}

// AddUpdatedAt adds u to the "updated_at" field.
func (tuo *TransactionUpdateOne) AddUpdatedAt(u int32) *TransactionUpdateOne {
	tuo.mutation.AddUpdatedAt(u)
	return tuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (tuo *TransactionUpdateOne) ClearUpdatedAt() *TransactionUpdateOne {
	tuo.mutation.ClearUpdatedAt()
	return tuo
}

// SetDeletedAt sets the "deleted_at" field.
func (tuo *TransactionUpdateOne) SetDeletedAt(u uint32) *TransactionUpdateOne {
	tuo.mutation.ResetDeletedAt()
	tuo.mutation.SetDeletedAt(u)
	return tuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableDeletedAt(u *uint32) *TransactionUpdateOne {
	if u != nil {
		tuo.SetDeletedAt(*u)
	}
	return tuo
}

// AddDeletedAt adds u to the "deleted_at" field.
func (tuo *TransactionUpdateOne) AddDeletedAt(u int32) *TransactionUpdateOne {
	tuo.mutation.AddDeletedAt(u)
	return tuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (tuo *TransactionUpdateOne) ClearDeletedAt() *TransactionUpdateOne {
	tuo.mutation.ClearDeletedAt()
	return tuo
}

// Mutation returns the TransactionMutation object of the builder.
func (tuo *TransactionUpdateOne) Mutation() *TransactionMutation {
	return tuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Transaction entity.
func (tuo *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	var (
		err  error
		node *Transaction
	)
	tuo.defaults()
	if len(tuo.hooks) == 0 {
		if err = tuo.check(); err != nil {
			return nil, err
		}
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransactionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tuo.check(); err != nil {
				return nil, err
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			if tuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, tuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Transaction)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from TransactionMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TransactionUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok && !tuo.mutation.UpdatedAtCleared() {
		v := transaction.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TransactionUpdateOne) check() error {
	if v, ok := tuo.mutation.Payload(); ok {
		if err := transaction.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "Transaction.payload": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tuo *TransactionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransactionUpdateOne {
	tuo.modifiers = append(tuo.modifiers, modifiers...)
	return tuo
}

func (tuo *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   transaction.Table,
			Columns: transaction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: transaction.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.EntID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: transaction.FieldEntID,
		})
	}
	if value, ok := tuo.mutation.CoinType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldCoinType,
		})
	}
	if value, ok := tuo.mutation.AddedCoinType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldCoinType,
		})
	}
	if tuo.mutation.CoinTypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: transaction.FieldCoinType,
		})
	}
	if value, ok := tuo.mutation.ChainType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldChainType,
		})
	}
	if value, ok := tuo.mutation.AddedChainType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldChainType,
		})
	}
	if tuo.mutation.ChainTypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: transaction.FieldChainType,
		})
	}
	if value, ok := tuo.mutation.ClientType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldClientType,
		})
	}
	if value, ok := tuo.mutation.AddedClientType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldClientType,
		})
	}
	if tuo.mutation.ClientTypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: transaction.FieldClientType,
		})
	}
	if value, ok := tuo.mutation.TransactionID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldTransactionID,
		})
	}
	if value, ok := tuo.mutation.Cid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldCid,
		})
	}
	if tuo.mutation.CidCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: transaction.FieldCid,
		})
	}
	if value, ok := tuo.mutation.ExitCode(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: transaction.FieldExitCode,
		})
	}
	if value, ok := tuo.mutation.AddedExitCode(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: transaction.FieldExitCode,
		})
	}
	if tuo.mutation.ExitCodeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Column: transaction.FieldExitCode,
		})
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldName,
		})
	}
	if tuo.mutation.NameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: transaction.FieldName,
		})
	}
	if value, ok := tuo.mutation.From(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldFrom,
		})
	}
	if tuo.mutation.FromCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: transaction.FieldFrom,
		})
	}
	if value, ok := tuo.mutation.To(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldTo,
		})
	}
	if tuo.mutation.ToCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: transaction.FieldTo,
		})
	}
	if value, ok := tuo.mutation.Memo(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldMemo,
		})
	}
	if tuo.mutation.MemoCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: transaction.FieldMemo,
		})
	}
	if value, ok := tuo.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: transaction.FieldAmount,
		})
	}
	if value, ok := tuo.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: transaction.FieldAmount,
		})
	}
	if tuo.mutation.AmountCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Column: transaction.FieldAmount,
		})
	}
	if value, ok := tuo.mutation.Payload(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: transaction.FieldPayload,
		})
	}
	if tuo.mutation.PayloadCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Column: transaction.FieldPayload,
		})
	}
	if value, ok := tuo.mutation.State(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldState,
		})
	}
	if value, ok := tuo.mutation.AddedState(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldState,
		})
	}
	if tuo.mutation.StateCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: transaction.FieldState,
		})
	}
	if value, ok := tuo.mutation.LockTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldLockTime,
		})
	}
	if value, ok := tuo.mutation.AddedLockTime(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldLockTime,
		})
	}
	if tuo.mutation.LockTimeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: transaction.FieldLockTime,
		})
	}
	if value, ok := tuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldCreatedAt,
		})
	}
	if value, ok := tuo.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldCreatedAt,
		})
	}
	if tuo.mutation.CreatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: transaction.FieldCreatedAt,
		})
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldUpdatedAt,
		})
	}
	if value, ok := tuo.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldUpdatedAt,
		})
	}
	if tuo.mutation.UpdatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: transaction.FieldUpdatedAt,
		})
	}
	if value, ok := tuo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldDeletedAt,
		})
	}
	if value, ok := tuo.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldDeletedAt,
		})
	}
	if tuo.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Column: transaction.FieldDeletedAt,
		})
	}
	_spec.Modifiers = tuo.modifiers
	_node = &Transaction{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
